# nixpacks.toml (Новая, более простая и надежная версия)

[phases.install]
# Указываем точные команды. Сначала ставим Python-пакеты.
# Затем запускаем установку Playwright с флагом --with-deps.
# Этот флаг сам скачает браузеры И установит все нужные системные зависимости.
cmds = [
    "pip install -r requirements.txt",
    "playwright install --with-deps"
]
