# nixpacks.toml (Финальная версия с ручным управлением зависимостями)

[phases.setup]
# Точный список системных библиотек для Playwright/Chromium на Ubuntu 22.04/24.04
# Этот список более полный и использует правильные имена для новых систем.
aptPkgs = [
    "libnss3", "libnspr4", "libdbus-1-3", "libatk1.0-0", "libatk-bridge2.0-0",
    "libcups2t64", "libdrm2", "libgbm1", "libxss1", "libatspi2.0-0", "libx11-6",
    "libxcomposite1", "libxdamage1", "libxext6", "libxfixes3", "libxrandr2",
    "libasound2t64", "pango1.0-tools", "libpangocairo-1.0-0", "libu2f-udev", "libvulkan1"
]

[phases.install]
# Выполняем команды по отдельности.
# Сначала pip, потом playwright install, но уже БЕЗ --with-deps
# Важно: мы активируем виртуальное окружение для КАЖДОЙ команды.
cmds = [
    "python -m venv --copies /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt",
    ". /opt/venv/bin/activate && playwright install"
]
