# nixpacks.toml

# Указываем, какие системные пакеты нужно установить с помощью apt-get
# Это зависимости, необходимые Playwright/Chromium для работы в headless-режиме на Linux
[phases.setup]
aptPkgs = [
    "libnss3", "libatk1.0-0", "libatk-bridge2.0-0", "libcups2",
    "libgtk-3-0", "libgbm-dev", "libxss1", "libasound2", "libdbus-glib-1-2"
]
